### ISSUE TITLE
Make design for 1.1.

### ISSUE THREAD

**Issue by serge-nikitin** [serge-nikitin/letsdiscuss.tech#45]

**Comment by eshill** [comment]
![sign in](https://cloud.githubusercontent.com/assets/11502920/25520476/b6396816-2c04-11e7-9618-502a7ff9d19f.png)
![users](https://cloud.githubusercontent.com/assets/11502920/25520479/bba3c4ae-2c04-11e7-9e5b-8e9d4b34c793.png)
![my_topics](https://cloud.githubusercontent.com/assets/11502920/25520489/c42a845a-2c04-11e7-9dc6-119e054f576b.png)
![view](https://cloud.githubusercontent.com/assets/11502920/25520491/c8819e62-2c04-11e7-9781-6137d02cf7cc.png)
![new](https://cloud.githubusercontent.com/assets/11502920/25520496/caf1b452-2c04-11e7-9351-918cf2d588c3.png)
![discuss](https://cloud.githubusercontent.com/assets/11502920/25520502/d0f480a0-2c04-11e7-9874-5a6239e17e5f.png)
![view2](https://cloud.githubusercontent.com/assets/11502920/25520532/eae5b36c-2c04-11e7-999c-8d45e490642b.png)

**Comment by progsmile** [comment]
Looks good)

**Comment by serge-nikitin** [comment]
@progsmile It's already an old version.

The current version of design looks like this: https://projects.invisionapp.com/share/8JC7X3RKX#/screens

But temporary I use Material Design for prototyping.

If you want to discuss letsdiscuss :) we can have a skype session. I'm free on Fridays and Saturdays at 6 pm UTC. Feel free to message me in skype: mail@sergenikitin.com
